
site_name: MXLS Guide
site_description: A MXLS Guide for beginners.
site_author: 'Vosa G Tom'
copyright: 'Copyright notice : All the content on this website is free of right also mods are gay'

theme:
  name: windmill-dark

markdown-extensions:
    - meta
    - attr_list


remote_branch: 'deploy_site'


nav:
  - Home: index.md
  - Chars and Skills: characters.md
  - Progression: progression.md
  - Items: items.md
  - Play online: tsw.md
  - Tools: tools.md
  - FAQ: faq.md
  - About: about.md
