site_name: MedianXLÎ£ Guide
theme: 'windmill-dark'
article_nav_top: 'false'

nav:
  - Home: index.md
  - Chars and Skills: characters.md
  - Progression: progression.md
  - Play online: tsw.md
  - About: about.md
