site_name: MedianXLÎ£ Guide
theme: 'windmill-dark'
site_author: 'Vosa G Tom'
copyright: 'Copyright notice : All the content on this website is free of right'
remote_branch: 'deploy_site'

nav:
  - Home: index.md
  - Chars and Skills: characters.md
  - Progression: progression.md
  - Play online: tsw.md
  - About: about.md
